[general]
import = [
#     "~/.config/alacritty/themes/themes/remedy_dark.toml"
    "~/.config/alacritty/themes/themes/tokyo_night_storm.toml"
]

[window]
decorations = "None"
opacity = 0.98
# opacity = 0.7
padding = { x = 5, y = 5 }
startup_mode = "Maximized"

[cursor]
style = { shape = "Beam", blinking = "On" }

[font]
size = 10.5

[mouse]
bindings = [
]
